### ISSUE TITLE
Predictions of clustering model in case of RFReg

### ISSUE THREAD

**Issue by terry07** [IngoMarquart/rfcc#1]
Thanks for this nice to see github. It seems really useful for various tasks.
I am trying to get some clusters on numeric X space for a regression task.

After having trained my cluster mode, i get the score (r^2), but the predict method returns the next one message:

model.predict(X)
Traceback (most recent call last):

  File "<ipython-input-54-43a58eb494e8>", line 1, in <module>
    model.predict(X)

  File "C:/Users/stam/Documents/git/rfcc/rfcc/model.py", line 269, in predict
    X,y,categoricals = self.__transform_data(X, y, False, self.categoricals, False)

  File "C:/Users/stam/Documents/git/rfcc/rfcc/model.py", line 452, in __transform_data
    y_numeric=y.select_dtypes(include=np.number).columns.tolist()

AttributeError: 'numpy.ndarray' object has no attribute 'select_dtypes'

Any help here?
Thanks for your time.

**Comment by IngoMarquart** [comment]
Thank you for catching this error.

I have pushed an update on github. Would you mind trying if this new commit fixes the issue?

**Comment by terry07** [comment]
Perfect, thanks!
